name: release

on: [pull_request]

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Dependencies
        run: go get -t ./...

      - name: Tidy
        run: go mod tidy
      
      - name: Generate
        run: go generate ./...
      
      - name: Test
        run: go test ./...
        # run: go test -v ./...
